/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessCodeRouteImport } from './routes/access-code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppVouchersRouteImport } from './routes/app.vouchers'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMyVouchersRouteImport } from './routes/app.my-vouchers'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppBreakfastRouteImport } from './routes/app.breakfast'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as AdminShopRouteImport } from './routes/admin.shop'
import { Route as AdminRedemptionsRouteImport } from './routes/admin.redemptions'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminBreakfastRouteImport } from './routes/admin.breakfast'
import { Route as AppVoucherIdRouteImport } from './routes/app.voucher.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessCodeRoute = AccessCodeRouteImport.update({
  id: '/access-code',
  path: '/access-code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMyVouchersRoute = AppMyVouchersRouteImport.update({
  id: '/my-vouchers',
  path: '/my-vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppBreakfastRoute = AppBreakfastRouteImport.update({
  id: '/breakfast',
  path: '/breakfast',
  getParentRoute: () => AppRoute,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedemptionsRoute = AdminRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBreakfastRoute = AdminBreakfastRouteImport.update({
  id: '/breakfast',
  path: '/breakfast',
  getParentRoute: () => AdminRoute,
} as any)
const AppVoucherIdRoute = AppVoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-code': typeof AccessCodeRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/breakfast': typeof AdminBreakfastRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/events': typeof AppEventsRoute
  '/app/my-vouchers': typeof AppMyVouchersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/shop': typeof AppShopRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/admin/': typeof AdminIndexRoute
  '/app/voucher/$id': typeof AppVoucherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-code': typeof AccessCodeRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/breakfast': typeof AdminBreakfastRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/events': typeof AppEventsRoute
  '/app/my-vouchers': typeof AppMyVouchersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/shop': typeof AppShopRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/admin': typeof AdminIndexRoute
  '/app/voucher/$id': typeof AppVoucherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-code': typeof AccessCodeRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/breakfast': typeof AdminBreakfastRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/redemptions': typeof AdminRedemptionsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/app/breakfast': typeof AppBreakfastRoute
  '/app/events': typeof AppEventsRoute
  '/app/my-vouchers': typeof AppMyVouchersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/shop': typeof AppShopRoute
  '/app/vouchers': typeof AppVouchersRoute
  '/admin/': typeof AdminIndexRoute
  '/app/voucher/$id': typeof AppVoucherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-code'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/breakfast'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/members'
    | '/admin/redemptions'
    | '/admin/shop'
    | '/admin/vouchers'
    | '/app/breakfast'
    | '/app/events'
    | '/app/my-vouchers'
    | '/app/profile'
    | '/app/shop'
    | '/app/vouchers'
    | '/admin/'
    | '/app/voucher/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-code'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/breakfast'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/members'
    | '/admin/redemptions'
    | '/admin/shop'
    | '/admin/vouchers'
    | '/app/breakfast'
    | '/app/events'
    | '/app/my-vouchers'
    | '/app/profile'
    | '/app/shop'
    | '/app/vouchers'
    | '/admin'
    | '/app/voucher/$id'
  id:
    | '__root__'
    | '/'
    | '/access-code'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/breakfast'
    | '/admin/contact'
    | '/admin/events'
    | '/admin/members'
    | '/admin/redemptions'
    | '/admin/shop'
    | '/admin/vouchers'
    | '/app/breakfast'
    | '/app/events'
    | '/app/my-vouchers'
    | '/app/profile'
    | '/app/shop'
    | '/app/vouchers'
    | '/admin/'
    | '/app/voucher/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessCodeRoute: typeof AccessCodeRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-code': {
      id: '/access-code'
      path: '/access-code'
      fullPath: '/access-code'
      preLoaderRoute: typeof AccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/vouchers': {
      id: '/app/vouchers'
      path: '/vouchers'
      fullPath: '/app/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-vouchers': {
      id: '/app/my-vouchers'
      path: '/my-vouchers'
      fullPath: '/app/my-vouchers'
      preLoaderRoute: typeof AppMyVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/breakfast': {
      id: '/app/breakfast'
      path: '/breakfast'
      fullPath: '/app/breakfast'
      preLoaderRoute: typeof AppBreakfastRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redemptions': {
      id: '/admin/redemptions'
      path: '/redemptions'
      fullPath: '/admin/redemptions'
      preLoaderRoute: typeof AdminRedemptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/breakfast': {
      id: '/admin/breakfast'
      path: '/breakfast'
      fullPath: '/admin/breakfast'
      preLoaderRoute: typeof AdminBreakfastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/voucher/$id': {
      id: '/app/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/app/voucher/$id'
      preLoaderRoute: typeof AppVoucherIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBreakfastRoute: typeof AdminBreakfastRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminRedemptionsRoute: typeof AdminRedemptionsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBreakfastRoute: AdminBreakfastRoute,
  AdminContactRoute: AdminContactRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminRedemptionsRoute: AdminRedemptionsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBreakfastRoute: typeof AppBreakfastRoute
  AppEventsRoute: typeof AppEventsRoute
  AppMyVouchersRoute: typeof AppMyVouchersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppShopRoute: typeof AppShopRoute
  AppVouchersRoute: typeof AppVouchersRoute
  AppVoucherIdRoute: typeof AppVoucherIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBreakfastRoute: AppBreakfastRoute,
  AppEventsRoute: AppEventsRoute,
  AppMyVouchersRoute: AppMyVouchersRoute,
  AppProfileRoute: AppProfileRoute,
  AppShopRoute: AppShopRoute,
  AppVouchersRoute: AppVouchersRoute,
  AppVoucherIdRoute: AppVoucherIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessCodeRoute: AccessCodeRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
